"""Bundle first-party assets into a self-contained, reproducible firmware page."""
from pathlib import Path
import gzip
import re


def bundle(project):
    root = Path(project) / 'data'
    html = (root / 'index.html').read_text(encoding='utf-8')
    def stylesheet(match):
        path = root / match[1].lstrip('/')
        return '<style>\n' + path.read_text(encoding='utf-8') + '\n</style>'
    def script(match):
        path = root / match[1].lstrip('/')
        return '<script>\n' + path.read_text(encoding='utf-8') + '\n</script>'
    html = re.sub(r'<link rel="stylesheet" href="([^"]+)">', stylesheet, html)
    html = re.sub(r'<script src="([^"]+)"></script>', script, html)
    if re.search(r'<(?:script[^>]+src|link[^>]+stylesheet[^>]+href)=', html):
        raise ValueError('Unbundled asset reference')
    return html.encode('utf-8')


def generate(project):
    raw = bundle(project)
    packed = gzip.compress(raw, compresslevel=9, mtime=0)
    lines = ['#pragma once', '#include <Arduino.h>',
             '// Generated by tools/package_web.py. Do not edit.',
             'static const uint32_t TCU_INDEX_HTML_GZ_LEN = %d;' % len(packed),
             'static const uint8_t TCU_INDEX_HTML_GZ[] PROGMEM = {']
    for i in range(0,len(packed),16):
        lines.append('  '+', '.join('0x%02X' % x for x in packed[i:i+16])+',')
    lines.append('};\n')
    text='\n'.join(lines)
    out=Path(project)/'include'/'tcu_index_html.h'
    out.parent.mkdir(parents=True,exist_ok=True)
    if not out.exists() or out.read_text(encoding='utf-8')!=text:
        out.write_text(text,encoding='utf-8')
    return len(raw),len(packed)


if __name__=='__main__':
    project=Path(__file__).resolve().parents[1]
    print('Web assets: %d bytes bundled -> %d bytes gzip' % generate(project))
